name: Publish new version

on:
    push:
        tags:
            - 'v*'

jobs:
    test:
        name: Test + Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 17

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run test
              env:
                  NODE_OPTIONS: --openssl-legacy-provider

    publish-collboard:
        name: Publish on Collboard module store
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 17

            - name: Install dependencies
              run: npm ci

            - name: Publish
              run: npx colldev publish --token ${{secrets.MODULE_STORE_ROOT_TOKEN}}
              env:
                  NODE_OPTIONS: --openssl-legacy-provider
